version: "2"
services:
  bootstrap:
    build: monitored-geth-client
    restart: on-failure
    container_name: bootstrap
    hostname: bootstrap
    links:
      - netstats
    entrypoint: /root/start.sh
    command: '--datadir=~/.ethereum/devchain --nodekeyhex=091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322  --syncmode "full" --rpcapi "db,personal,eth,net,web3" --rpccorsdomain="*" --networkid=1212 --rpc --rpcaddr="0.0.0.0"'
    volumes:
      - ./files/password:/root/files/password:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - ./files/keystore:/root/.ethereum/devchain/keystore:rw
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
  eth-miner1:
    build: monitored-geth-client
    restart: on-failure
    links:
      - bootstrap
      - netstats
    entrypoint: /root/start.sh
    volumes:
      - ./files/password/pass.txt:/root/files/password.txt:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - ./files/node1:/root/.ethereum/devchain/keystore:rw
      - /etc/localtime:/etc/localtime:ro
    command: '--datadir=~/.ethereum/devchain --port 30311 --syncmode "full" --rpccorsdomain="*" --networkid=1212 --rpc --bootnodes="enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@35.198.95.42:30303" --gasprice "1" -unlock "0x007ccffb7916f37f7aeef05e8096ecfbe55afc2f" --password /root/files/password.txt  --mine'
    ports:
      - "30311:30311"
  eth-miner2:
    build: monitored-geth-client
    restart: on-failure
    links:
      - bootstrap
      - netstats
    entrypoint: /root/start.sh
    volumes:
      - ./files/password/pass.txt:/root/files/password.txt:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - ./files/node2:/root/.ethereum/devchain/keystore:rw
      - /etc/localtime:/etc/localtime:ro
    command: '--datadir=~/.ethereum/devchain --syncmode "full" --rpccorsdomain="*" --networkid=1212 --rpc --bootnodes="enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@35.198.95.42:30303" --gasprice "1" -unlock "0x276ecb88715a503b00d1f15af4c17dc051991667" --password /root/files/password.txt --mine'

  eth-miner3:
    build: monitored-geth-client
    restart: on-failure
    container_name: eth-miner3
    links:
      - bootstrap
      - netstats
    entrypoint: /root/start.sh
    volumes:
      - ./files/password/pass.txt:/root/files/password.txt:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - ./files/node3:/root/.ethereum/devchain/keystore:rw
      - /etc/localtime:/etc/localtime:ro
    command: '--datadir=~/.ethereum/devchain --syncmode "full" --rpccorsdomain="*" --networkid=1212 --rpc --bootnodes="enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@35.198.95.42:30303" --gasprice "1" -unlock "0x794f74c8916310d6a0009bb8a43a5acab59a58ad" --password /root/files/password.txt --mine'

  netstats:
    build: eth-netstats
    restart: on-failure
    container_name: netstats
    environment:
      - WS_SECRET=eth-net-stats-secret
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
